### ISSUE TITLE
SideInputs should be implemented transparently using broadcast variables

### ISSUE THREAD

**Issue by jhlch** [cloudera/spark-dataflow#10]
RuntimeContext should allow access to broadcast variables. This will make it easier to specify and access side inputs.

**Comment by rekbun** [comment]
@jhlch Can you elaborate this issue a little.I want to contribute to this project.

**Comment by tomwhite** [comment]
@jhlch I've updated the side input code to be more robust (see https://github.com/cloudera/spark-dataflow/commit/72d22d0b7ffc099c92d8dbc1fbe11dd411460176), however I think your changes would still be useful.

**Comment by tomwhite** [comment]
The code repackaging part will be superceded by the move to Apache Beam, so closing this.
