### ISSUE TITLE
Maven repository coordinates go nowhere

### ISSUE THREAD

**Issue by ksookocheff-va** [cloudera/spark-dataflow#21]
Adding the maven repository coordinates to my project results in an error that the repo cannot be found.

**Comment by srowen** [comment]
Heh, yeah I'm not sure it's even been published yet. It will be in the Cloudera repo, but I don't see it yet. @jhlch I have set this kind of thing up before, should I take a crack?

**Comment by jwills** [comment]
Hey @srowen, yeah, that's my bad-- my new laptop didn't have the cloudera repo credentials. Would you mind?

**Comment by srowen** [comment]
Should be OK now: https://repository.cloudera.com/artifactory/cloudera-repos/com/cloudera/dataflow/spark/spark-dataflow/0.0.1/
