### ISSUE TITLE
COmpiled correctly , SocketConnector and SL

### ISSUE THREAD

**Issue by sshubhe** [cloudera/spark-dataflow#24]
file:///home/cloudera/Desktop/SparkTest
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:java (default-cli) on project google-cloud-dataflow-java-examples-all: An exception occured while executing the Java class. null: InvocationTargetException: org/eclipse/jetty/server/bio/SocketConnector: org.eclipse.jetty.server.bio.SocketConnector ->

Facing this issue while using the wordcount of google cloud dataflow to run on spark runner.Please suggest

**Comment by jhlch** [comment]
[Invocation target exception](http://docs.oracle.com/javase/7/docs/api/java/lang/reflect/InvocationTargetException.html) is a wrapper for an exception thropwn by an invoked method or a contructor. Can you tell me what maven command you are trying to run from the root dir of the project and include the full stack trace that is returned?

**Comment by sshubhe** [comment]
Hi Juliet,

Please find the details regarding the commands which I used.I was trying to
use the Spark Pipeline runner in place of Dataflow Pipeline runner.Please
let me know in case further details are required.

-Shubh

On Mon, Mar 16, 2015 at 1:39 PM, Juliet Hougland <notifications@github.com>
wrote:

> Invocation target exception
> <http://docs.oracle.com/javase/7/docs/api/java/lang/reflect/InvocationTargetException.html>
> is a wrapper for an exception thropwn by an invoked method or a contructor.
> Can you tell me what maven command you are trying to run from the root dir
> of the project and include the full stack trace that is returned?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/spark-dataflow/issues/24#issuecomment-81832236>
> .
>

[cloudera@quickstart ~]$ ls
apache-maven-3.1.1-bin.zip  datasets   Downloads  GitRepo  Pictures   Videos
cloudera-manager            Desktop    eclipse    lib      Public     workspace
cm_api.sh                   Documents  git        Music    Templates
[cloudera@quickstart ~]$ cd git
[cloudera@quickstart git]$ ls
DataflowJavaSDK  input.txt
[cloudera@quickstart git]$ cd DataflowJavaSDK/
[cloudera@quickstart DataflowJavaSDK]$ ls
checkstyle.xml  CONTRIBUTING.md  examples  pom.xml    sdk
contrib         eclipse          LICENSE   README.md  test_wordcount.sh
[cloudera@quickstart DataflowJavaSDK]$ mvn install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Google Cloud Dataflow Java SDK - Parent
[INFO] Google Cloud Dataflow Java SDK - All
[INFO] Google Cloud Dataflow Java Examples - All
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Dataflow Java SDK - Parent manual_build
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ google-cloud-dataflow-java-sdk-parent ---
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/pom.xml to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-parent/manual_build/google-cloud-dataflow-java-sdk-parent-manual_build.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Dataflow Java SDK - All manual_build
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:prepare-agent (default) @ google-cloud-dataflow-java-sdk-all ---
[INFO] argLine set to -javaagent:/home/cloudera/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/home/cloudera/git/DataflowJavaSDK/sdk/target/jacoco.exec,dumponexit=true,output=file
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ google-cloud-dataflow-java-sdk-all ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (dataflow-sdk-compile) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Building jar: /home/cloudera/git/DataflowJavaSDK/sdk/target/google-cloud-dataflow-java-sdk-all-manual_build.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ google-cloud-dataflow-java-sdk-all >>>
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:prepare-agent (default) @ google-cloud-dataflow-java-sdk-all ---
[INFO] argLine set to -javaagent:/home/cloudera/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/home/cloudera/git/DataflowJavaSDK/sdk/target/jacoco.exec,dumponexit=true,output=file
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ google-cloud-dataflow-java-sdk-all <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ google-cloud-dataflow-java-sdk-all ---
[INFO] 
[INFO] --- avro-maven-plugin:1.7.7:schema (schemas) @ google-cloud-dataflow-java-sdk-all ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:add-test-source (add-test-source) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Test Source directory: /home/cloudera/git/DataflowJavaSDK/sdk/target/generated-test-sources/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ google-cloud-dataflow-java-sdk-all ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cloudera/git/DataflowJavaSDK/sdk/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-jar-plugin:2.5:test-jar (dataflow-sdk-test-compile) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Building jar: /home/cloudera/git/DataflowJavaSDK/sdk/target/google-cloud-dataflow-java-sdk-all-manual_build-tests.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.4:test-jar (attach-test-sources) @ google-cloud-dataflow-java-sdk-all >>>
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:prepare-agent (default) @ google-cloud-dataflow-java-sdk-all ---
[INFO] argLine set to -javaagent:/home/cloudera/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/home/cloudera/git/DataflowJavaSDK/sdk/target/jacoco.exec,dumponexit=true,output=file
[INFO] 
[INFO] <<< maven-source-plugin:2.4:test-jar (attach-test-sources) @ google-cloud-dataflow-java-sdk-all <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:test-jar (attach-test-sources) @ google-cloud-dataflow-java-sdk-all ---
[INFO] 
[INFO] --- maven-surefire-plugin:2.15:test (default-test) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:report (report) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/home/cloudera/git/DataflowJavaSDK/sdk/target/jacoco.exec
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ google-cloud-dataflow-java-sdk-all ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.12:check (default) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Starting audit...
Audit done.

[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ google-cloud-dataflow-java-sdk-all ---
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/sdk/target/google-cloud-dataflow-java-sdk-all-manual_build.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/manual_build/google-cloud-dataflow-java-sdk-all-manual_build.jar
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/sdk/pom.xml to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/manual_build/google-cloud-dataflow-java-sdk-all-manual_build.pom
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/sdk/target/google-cloud-dataflow-java-sdk-all-manual_build-sources.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/manual_build/google-cloud-dataflow-java-sdk-all-manual_build-sources.jar
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/sdk/target/google-cloud-dataflow-java-sdk-all-manual_build-tests.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/manual_build/google-cloud-dataflow-java-sdk-all-manual_build-tests.jar
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/sdk/target/google-cloud-dataflow-java-sdk-all-manual_build-test-sources.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/manual_build/google-cloud-dataflow-java-sdk-all-manual_build-test-sources.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Dataflow Java Examples - All manual_build
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ google-cloud-dataflow-java-examples-all ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cloudera/git/DataflowJavaSDK/examples/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ google-cloud-dataflow-java-examples-all ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ google-cloud-dataflow-java-examples-all >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ google-cloud-dataflow-java-examples-all <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ google-cloud-dataflow-java-examples-all ---
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (dataflow-examples-compile) @ google-cloud-dataflow-java-examples-all ---
[INFO] Building jar: /home/cloudera/git/DataflowJavaSDK/examples/target/google-cloud-dataflow-java-examples-all-manual_build.jar
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ google-cloud-dataflow-java-examples-all ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cloudera/git/DataflowJavaSDK/examples/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ google-cloud-dataflow-java-examples-all ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] >>> maven-source-plugin:2.4:test-jar (attach-test-sources) @ google-cloud-dataflow-java-examples-all >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.4:test-jar (attach-test-sources) @ google-cloud-dataflow-java-examples-all <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:test-jar (attach-test-sources) @ google-cloud-dataflow-java-examples-all ---
[INFO] 
[INFO] --- maven-jar-plugin:2.5:test-jar (dataflow-examples-test-compile) @ google-cloud-dataflow-java-examples-all ---
[INFO] Building jar: /home/cloudera/git/DataflowJavaSDK/examples/target/google-cloud-dataflow-java-examples-all-manual_build-tests.jar
[INFO] 
[INFO] --- maven-surefire-plugin:2.15:test (default-test) @ google-cloud-dataflow-java-examples-all ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ google-cloud-dataflow-java-examples-all ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.12:check (default) @ google-cloud-dataflow-java-examples-all ---
[INFO] Starting audit...
Audit done.

[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ google-cloud-dataflow-java-examples-all ---
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/examples/target/google-cloud-dataflow-java-examples-all-manual_build.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-examples-all/manual_build/google-cloud-dataflow-java-examples-all-manual_build.jar
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/examples/pom.xml to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-examples-all/manual_build/google-cloud-dataflow-java-examples-all-manual_build.pom
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/examples/target/google-cloud-dataflow-java-examples-all-manual_build-sources.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-examples-all/manual_build/google-cloud-dataflow-java-examples-all-manual_build-sources.jar
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/examples/target/google-cloud-dataflow-java-examples-all-manual_build-test-sources.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-examples-all/manual_build/google-cloud-dataflow-java-examples-all-manual_build-test-sources.jar
[INFO] Installing /home/cloudera/git/DataflowJavaSDK/examples/target/google-cloud-dataflow-java-examples-all-manual_build-tests.jar to /home/cloudera/.m2/repository/com/google/cloud/dataflow/google-cloud-dataflow-java-examples-all/manual_build/google-cloud-dataflow-java-examples-all-manual_build-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Google Cloud Dataflow Java SDK - Parent ........... SUCCESS [0.632s]
[INFO] Google Cloud Dataflow Java SDK - All .............. SUCCESS [25.037s]
[INFO] Google Cloud Dataflow Java Examples - All ......... SUCCESS [5.639s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.976s
[INFO] Finished at: Fri Mar 20 20:28:08 PDT 2015
[INFO] Final Memory: 22M/53M
[INFO] ------------------------------------------------------------------------
[cloudera@quickstart DataflowJavaSDK]$ ls
checkstyle.xml  CONTRIBUTING.md  examples  pom.xml    sdk
contrib         eclipse          LICENSE   README.md  test_wordcount.sh
[cloudera@quickstart DataflowJavaSDK]$ mvn exec:java -pl examples -Dexec.mainClass=com.google.cloud.dataflow.examples.WordCount -Dexec.args="--input=/home/cloudera/git/input.txt --output=/home/cloudera/git/Test1"
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Dataflow Java Examples - All manual_build
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.1:java (default-cli) @ google-cloud-dataflow-java-examples-all >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.1:java (default-cli) @ google-cloud-dataflow-java-examples-all <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.1:java (default-cli) @ google-cloud-dataflow-java-examples-all ---
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/cloudera/.m2/repository/org/slf4j/slf4j-jdk14/1.7.7/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/cloudera/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.842s
[INFO] Finished at: Fri Mar 20 20:30:46 PDT 2015
[INFO] Final Memory: 16M/39M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:java (default-cli) on project google-cloud-dataflow-java-examples-all: An exception occured while executing the Java class. null: InvocationTargetException: StackOverflowError -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[cloudera@quickstart DataflowJavaSDK]$

**Comment by tomwhite** [comment]
I recently updated the top-level README to cover how to run the word count example using `mvn exec:exec` (for local mode) and `spark-submit` (for a cluster). I'm closing this now, but please re-open if the problem persists.
