### ISSUE TITLE
ClassNotFoundException: com.cloudera.dataflow.spark.aggregators.AggAccumParam

### ISSUE THREAD

**Issue by psybers** [cloudera/spark-dataflow#25]
I attempted to modify the Cloud Dataflow Wordcount example to use this library as the runner.  This works if I let Spark run as a single/local worker.  When connecting it to my actual cluster however, the tasks fail with a ClassNotFoundException.  I am attaching the full log in a gist below.

[ERROR] Caused by: java.lang.ClassNotFoundException: com.cloudera.dataflow.spark.aggregators.AggAccumParam

https://gist.github.com/psybers/be7798ee8ee23461c0af

All I did to modify their example was add the Cloudera repository to the examples/pom.xml and then add a dep to spark-dataflow.  It seems to have some of the classes, if you scan the log you will see TransformTranslator.java is loaded:

https://gist.github.com/psybers/be7798ee8ee23461c0af#file-gistfile1-txt-L59

**Comment by jwills** [comment]
That's odd-- which version of Spark are you running?

**Comment by psybers** [comment]
I'm testing this on Cloudera's CDH 5.3 Live VM.  So I believe that is Spark 1.2.0.

**Comment by jwills** [comment]
Oh, interesting. Curious if you get the problem when running w/the spark-submit script vs. mvn exec. I know that Spark can be a little particular about its classpath config stuff.

**Comment by psybers** [comment]
When I managed to finally figure out the full classpath maven was using, used that as the SPARK_CLASSPATH (and also pass them in via --jars) then yes, it works without error using spark-submit.

It would be nice if I could get this working using the mvn exec command though, since managing this classpath is extremely tedious!

**Comment by jhlch** [comment]
That is a great idea. I think we should close this issue and open a separate one with "make mvn exec work correctly" as the clear objective. Thanks for the follow up on this!
