### ISSUE TITLE
Write a CoderSerializer

### ISSUE THREAD

**Issue by tomwhite** [cloudera/spark-dataflow#31]
A Spark serializer that uses Coders for serialization.

**Comment by tomwhite** [comment]
I started writing this here: https://github.com/tomwhite/spark-dataflow/commit/b2373d7580ea3e34ce8e99a496109340392ba9f7. The main items to address are:
* The word count test fails with "No coder found for class interface scala.collection.Seq" (coming from trying to serialize ParallelCollectionPartition), so we'll need to add a Coder for Seq, at the minimum. It's actually likely that there will be other Scala or Spark-isms that will need Coders writing for them.
* The job needs to get all the Coders registered for a Pipeline and serialize them so that the CoderSerializer can access them on the remote executors.

**Comment by tomwhite** [comment]
I added a SeqCoder here: https://github.com/cloudera/spark-dataflow/compare/master...tomwhite:coder-serialization. Serialization is now successful.

Deserialization doesn't work however, since there is not enough type information to get the right coder. For example, when deserializing a Seq<T> Spark does not tell the deserializer the element type T, so it can't get the correct coder. (For example, if T is String, then you would construct a Coder<Seq<String>>.)

We could fix this by writing a tag to the stream that identifies the class (just like Kryo does), so that the deserializer can pick the right coder.

**Comment by srowen** [comment]
(PS need some copyright headers there)

Yeah this is the problem that Java serialization has in spades -- it adds that class name which can be huge overhead. Does the deserializing caller not know what type to expect in this context?

**Comment by tomwhite** [comment]
(Yes, this is just exploratory at the moment so doesn't pass checkstyle or RAT.)

The deserializer does not have the full type information; the problem is that Spark is passing a ClassTag (so something like Seq), rather than a TypeTag (Seq<String>).

Unlike Kryo, where the element class of a collection is optional (https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/CollectionSerializer.java#L100), Coders seem to require it.

**Comment by jwills** [comment]
This seems solvable to me, b/c the Serializer can take a SparkConf instance to a single-arg constructor, so we could serialize the N different Coders we would need to use for a given pipeline to field(s) in SparkConf and then retrieve them in the Serializer. We would still need to write out vints to signal which coder to use for any given set of bytes, but such is life-- I don't see a way to avoid that.

**Comment by tomwhite** [comment]
That sounds like the right direction to me. Before submitting the Spark job we can inspect the pipeline to determine which Coders are needed, then serialize them in a list in the conf.

However, when serializing we have to infer the Coder from the object, since the Serializer doesn't have enough context otherwise (e.g. if a pipeline had `List<String>` and `List<Integer>` the serializer wouldn't be able to distinguish the two when told that the type is `List` - this may actually be a problem if the collection is empty). This could be improved if Spark could signal the RDD that the serializer was being used for (e.g. by name), then we would know the types to expect - but that's not currently possible. It is possible to set the Serializer explicitly on the RDD in some cases (e.g. ShuffledRDD), but this is not always possible.

Before writing the serialized bytes to the stream we'd write the index of the Coder in the list as a vint. Deserialization would then be straightforward.

**Comment by tomwhite** [comment]
I looked at this more and Spark seems to serialize more than just the objects in the RDD. Things like the configuration and other ancillary objects are serialized, which would mean we'd have to write coders for these things (or possibly write some kind of Serializable wrapper).

So I've taken another approach, one that was started in the code and which is what the Spark implementation in Crunch does, which is to convert RDDs of objects to and from RDDs of byte arrays whenever they go through the shuffle (in a grouping or combining operation). See https://github.com/cloudera/spark-dataflow/pull/47

**Comment by tomwhite** [comment]
Closing this as the current approach is working well.
