### ISSUE TITLE
Update to dataflow 0.4.150602

### ISSUE THREAD

**Issue by tomwhite** [cloudera/spark-dataflow#49]
There have been quite a few breaking API changes as well as changes to the internals: https://cloud.google.com/dataflow/release-notes/java

I've started working on a fix here: https://github.com/cloudera/spark-dataflow/compare/master...tomwhite:dataflow-0.4.150602

The main thing that's remaining is fixing TfIdfTest, which is broken as GBK now uses windows in the dataflow implementation. We should probably go back to using a global window for the time being, like the direct runner does here: https://github.com/GoogleCloudPlatform/DataflowJavaSDK/commit/2eff8261a36d23798a8fbd97bcca61695122bfa8

**Comment by lbergelson** [comment]
We're updating hellbender to 0.4.150602 since it's needed for the skeleton pipeline work.   Spark will be broke on hellbender until this gets updated.

**Comment by jwills** [comment]
@lbergelson thanks for the heads up Louis-- I'm sure @tomwhite will get the fix in tomorrow and cut a new release.

**Comment by tomwhite** [comment]
This is fixed in release 0.2.0, which should now be available.
