### ISSUE TITLE
Refactor Serialization Logic

### ISSUE THREAD

**Issue by jhlch** [cloudera/spark-dataflow#6]
The is custom serialization logic relying on CoderHelpers and BroadcastHelpers, etc. This logic should be contained in a single [spark serializer](http://spark.apache.org/docs/latest/api/java/index.html) -- look in org.apache.spark.serializer. We could use kryo, and register custom kryo serializer from the default coder registry associated with a pipeline. Alternatively, we could define our own entirely Coder based spark serializer.

**Comment by jwills** [comment]
It wasn't obvious to me that a coder-based serializer could work b/c at least some of the Coder-related classes aren't serializable, right? We would need like "Chill for Coders" or something to make this work, no?

**Comment by tomwhite** [comment]
I've submitted a PR to at least switch over to use Kryo, since it can serialize more types than Java serialization, and it's faster. See https://github.com/cloudera/spark-dataflow/pull/29.

Longer term, having a CoderSerializer might make a lot of sense, so it's more like the Google implementation.

**Comment by tomwhite** [comment]
Closing, as the serialization logic is working well now.
